version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - webnet
      - dbnet
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8082:80"
    networks:
      - dbnet

volumes:
  db_data:

networks:
  webnet:
  dbnet: